shunting_vehicle:
  # Publish all joint states 
  # -----------------------------------
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  # Position Controllers 
  # ---------------------------------------
  front_left_wheel_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: front_left_wheel_white_joint
      pid: {p: 500.0, i: 100.0, d: 0.0}
      
  front_right_wheel_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: front_right_wheel_white_joint
      pid: {p: 500.0, i: 100.0, d: 0.0}

  rear_left_wheel_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: rear_left_wheel_white_joint
      pid: {p: 500.0, i: 100.0, d: 0.0}

  rear_right_wheel_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: rear_right_wheel_white_joint
      pid: {p: 500.0, i: 100.0, d: 0.0}

  front_axle_position_controller:
      type: effort_controllers/JointPositionController
      joint: front_axle_joint
      pid: {p: 100000.0, i: 1000.0, d: 10000.0}

  rear_axle_position_controller:
      type: effort_controllers/JointPositionController
      joint: rear_axle_joint
      pid: {p: 100000.0, i: 1000.0, d: 10000.0}

